// lib/listings.js — the marketplace's CURATED seed of x402 v2 services (option 1). You own this list;
// edit it to add/curate services you stand behind. Only REAL, verifiable x402 v2 endpoints belong here.
// (Open submissions from anyone are option 2 — see lib/registry.js — and are gated by a live /validate.)

const CHAT = 'https://kaspa-402-chat.kaspadev.workers.dev/exact';
const PAYTO = 'kaspa:qzws2a0lfhs9y8kkvyd4mm96gl733pd0mhzvh6mdejms7970gzrawmvjwpde4';

// One mainnet chat model, selected via ?model= on the shared chat gateway. Each model is priced
// independently (KASPA_X402_PRICE_USD_MAP on the gateway) — small models sit at the 0.5 KAS dust
// floor, larger ones command more; priceUsd here mirrors that map so the catalog matches the live offer.
const chatModel = (alias, name, capability, note, priceUsd) => ({
  id: `kaspa-402-chat-${alias}`,
  resource: `${CHAT}?model=${alias}`,
  serviceName: `Kaspa·402 — ${name}`,
  description: `${note} Append \`?prompt=…\` to the URL; each call settles $${priceUsd.toFixed(2)} (paid in KAS at the current rate, min 0.5 KAS) via x402 \`exact\` (standard-native) on mainnet and returns a reply.`,
  capability,
  scheme: 'exact',
  network: 'kaspa:mainnet',
  priceUsd,
  amountSompi: 50000000,
  payTo: PAYTO,
  tags: ['llm', 'mainnet', alias],
  source: 'seed',
  verified: true,
});

export const SEED = [
  {
    id: 'kaspa-402-summarize',
    resource: 'https://kaspa-402-summarize.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — summarize',
    description: 'Pay-per-call text summarization on llama3.1:8b, on kaspa:testnet-10 (validation target — settled in valueless TKAS). Append `?text=…` to the URL; each call settles a $0.05-equivalent amount (min 0.5 TKAS) via x402 `exact` (standard-native) and returns a 1–2 sentence summary.',
    capability: 'summarize',
    scheme: 'exact',
    network: 'kaspa:testnet-10',
    priceUsd: 0.05,
    amountSompi: 50000000,
    payTo: 'kaspatest:qr50gmc7t3jp33gg68aj63s9av54yc7w9kyjpwqdjhva9tt8j0a7wz2h6cnll',
    tags: ['llm', 'summarize', 'testnet'],
    source: 'seed',
    verified: true,
  },
  chatModel('chat', 'chat', 'llm:chat', 'General chat on llama3.1:8b.', 0.03),
  chatModel('fast', 'fast chat', 'llm:chat', 'Low-latency chat on qwen2.5:3b.', 0.01),
  chatModel('chat-mini', 'chat-mini', 'llm:chat', 'Balanced chat on qwen2.5:7b.', 0.01),
  chatModel('reason', 'reason', 'llm:reason', 'Deeper reasoning on qwen3.5:35b.', 0.08),
  chatModel('think', 'think', 'llm:reason', 'Reasoning-tuned qwen-think.', 0.10),
  chatModel('uncensored', 'uncensored', 'llm:chat', 'Unfiltered chat on Qwen3.6-35B.', 0.08),
  {
    id: 'kaspa-402-embed',
    resource: 'https://kaspa-402-embed.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — embed',
    description: 'Text embeddings on nomic-embed-text. Append `?input=…`; each call settles $0.01 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet and returns a 768-dim vector.',
    capability: 'embed',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.01,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['llm', 'embed', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-research',
    resource: 'https://kaspa-402-research.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — token risk report',
    description: 'On-chain due-diligence for KRC-20 tokens and KRC-721 NFTs — holder concentration, mint status, liquidity, and legitimacy signals, plus a plain-language risk summary. Append `?asset=krc20:NACHO` (or `krc721:KASPUNKS`); each call settles $0.10 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. On-chain facts, not financial advice.',
    capability: 'token-risk',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.10,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['research', 'krc20', 'krc721', 'risk', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-wallet',
    resource: 'https://kaspa-402-wallet.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — wallet risk profile',
    description: 'On-chain profile + risk read for any Kaspa address — KAS balance, activity, KRC-20 holdings, exposure to risky tokens (via the token-risk engine), and deployer detection. Append `?address=kaspa:…`; each call settles $0.10 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. On-chain facts from public data, not an accusation.',
    capability: 'wallet-risk',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.10,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['research', 'wallet', 'risk', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-ask',
    resource: 'https://kaspa-402-ask.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Kaspa expert (grounded Q&A)',
    description: "Grounded answers about Kaspa from a retrieval knowledge base — won't hallucinate Kaspa facts, and returns its sources. Append `?question=…`; each call settles $0.03 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. Ask about GHOSTDAG, KRC-20, covenants, Crescendo/Toccata, fees, and more.",
    capability: 'kaspa-expert',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.03,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['llm', 'kaspa-expert', 'rag', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-compare',
    resource: 'https://kaspa-402-compare.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — token comparison',
    description: 'Side-by-side risk comparison of 2–5 KRC-20 tokens — ranked safest-first on holder concentration, mint status, liquidity, and legitimacy, with a comparative writeup. Append `?assets=NACHO,KOMA,KANDA`; each call settles $0.15 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. On-chain facts, not financial advice.',
    capability: 'token-compare',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.15,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['research', 'krc20', 'compare', 'risk', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-radar',
    resource: 'https://kaspa-402-radar.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — mint & launch radar',
    description: "A live feed of what's hot and whether it's safe across KRC-20 tokens and KRC-721 NFTs — sorted by momentum (holder growth), recency, or minting activity, each with quick risk flags (pre-mint, tiny holder counts, still minting). Append `?type=krc20|krc721&sort=hot|new|minting&limit=10`; each call settles $0.05 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. On-chain facts, not financial advice.",
    capability: 'mint-radar',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.05,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['research', 'krc20', 'krc721', 'radar', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-ghost',
    resource: 'https://kaspa-402-ghost.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Ghost Trail (fund tracer)',
    description: "Follow the money. Feed a Kaspa address or a txid and trace the flow — top sources (who funded it), top destinations (who it paid), net flow, and distinct counterparties, with a forensic read. Append `?target=kaspa:…` (or a 64-hex txid); each call settles $0.10 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. Public on-chain data.",
    capability: 'fund-trace',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.10,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['forensics', 'trace', 'chain', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-shadow',
    resource: 'https://kaspa-402-shadow.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Whale Shadow (wallet tail)',
    description: "Tail a whale. Feed a Kaspa address and get a read on what it's doing right now — its size (KAS + KRC-20 holdings), whether it's accumulating or distributing KAS, and which tokens it's loading up on vs offloading. Append `?address=kaspa:…`; each call settles $0.10 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. Public on-chain data.",
    capability: 'whale-watch',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.10,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['forensics', 'whale', 'chain', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-coroner',
    resource: 'https://kaspa-402-coroner.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Rug Coroner (token autopsy)',
    description: "Token autopsy. Feed a KRC-20 ticker and get a health verdict — alive, critical, on life support, or likely dead — with the cause-of-death signs: liquidity failure, pre-mint, deployer holding, concentration, holder flight. Append `?ticker=KANDA`; each call settles $0.10 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. On-chain diagnosis from public data, not an accusation.",
    capability: 'rug-autopsy',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.10,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['forensics', 'rug', 'krc20', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-sybil',
    resource: 'https://kaspa-402-sybil.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Sybil Hunter',
    description: "Flag the bots. Feed a KRC-20 ticker and scan its holders for coordinated / sybil clusters — wallets holding identical amounts, the fingerprint of farms and insider distribution. Append `?ticker=KANDA`; each call settles $0.10 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. Top-holder sample; a suspicion signal, not proof.",
    capability: 'sybil-scan',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.10,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['forensics', 'sybil', 'krc20', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-exposure',
    resource: 'https://kaspa-402-exposure.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Exposure Report (OPSEC score)',
    description: "How traceable are you? Feed a Kaspa address and get an OPSEC / traceability score — linked alter-egos (co-spending), counterparty footprint, on-chain surface — plus concrete hardening advice. Append `?address=kaspa:…`; each call settles $0.10 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. Public on-chain data.",
    capability: 'opsec-score',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.10,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['forensics', 'opsec', 'privacy', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-cluster',
    resource: 'https://kaspa-402-cluster.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Cluster Mapper (unmask the entity)',
    description: "Unmask the entity. Feed a Kaspa address and get its co-spending cluster — the addresses provably controlled by the same owner, with per-address balances and the total KAS the entity controls. Append `?address=kaspa:…`; each call settles $0.15 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. Co-spending heuristic on public data, not proof of control.",
    capability: 'entity-cluster',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.15,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['forensics', 'cluster', 'deanon', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-redteam',
    resource: 'https://kaspa-402-redteam.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Covenant Red-Team (footgun linter)',
    description: "Red-team a Kaspa covenant before you ship it. Submit Silverscript source (compiled on-box with silverc), raw script hex, or a spent covenant address, and get a severity-ranked scan of the known Toccata footguns — unchecked outputs, baked covenant-ids, storage-mass floor, replay/freshness, the 520-byte reveal, fee model — plus the template hash. Append `?scriptHex=…`; each call settles $0.20 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. A heuristic linter, not an audit: flags to review, never a safe/unsafe verdict and never exploit paths.",
    capability: 'covenant:redteam',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.20,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['covenants', 'security', 'silverscript', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-reserve',
    resource: 'https://kaspa-402-reserve.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Proof-of-Reserve (control-proven)',
    description: "Prove — don't just claim — how much KAS is controlled. Two modes. Address: the claimant signs a recent Kaspa block hash with each address key; you get a signed, self-verifiable attestation of the total KAS provably controlled at that point in time (pass the request base64url-encoded as `?req=…`). Covenant: append `?covenantAddress=kaspa:…` (or a `kaspatest:…` testnet-10 covenant) to attest the KAS a covenant script controls on-chain — no signing, control is the script. Each call settles $0.15 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. Point-in-time proof of reserves (assets), not solvency.",
    capability: 'proof-of-reserve',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.15,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['attestation', 'proof-of-reserve', 'treasury', 'mainnet'],
    source: 'seed',
    verified: true,
  },
];

// --- Base-native services (outbound corridor) ---------------------------------------------------
// These live on Base, not Kaspa. You still pay in KAS: you call the kaspa-x402-router's outbound
// gateway (a real Kaspa x402 endpoint), pay KAS, and the router pays the Base x402 service in USDC on
// your behalf and returns the result. `base` describes the leg the router settles for you.
const OUTBOUND = 'https://kaspa-402-outbound.kaspadev.workers.dev/exact';        // standard tier (~0.5 KAS)
const OUTBOUND_HI = 'https://kaspa-402-outbound-hi.kaspadev.workers.dev/exact';  // higher tier (~60 KAS)

const baseSvc = ({ target, name, capability, description, baseHost, baseUsd, tier = 'standard', tags }) => ({
  id: `base-402-${target}`,
  kind: 'base',
  resource: `${tier === 'hi' ? OUTBOUND_HI : OUTBOUND}?target=${target}`,
  serviceName: `Base·402 — ${name}`,
  description,
  capability,
  scheme: 'exact',
  network: 'kaspa:mainnet',
  priceUsd: 0, // priced in KAS at the gateway tier (shown as sompi·KAS), not a USD peg on this leg
  amountSompi: tier === 'hi' ? 6000000000 : 50000000,
  payTo: PAYTO,
  base: { host: baseHost, network: 'eip155:8453', usd: baseUsd },
  tags: [...tags, 'base', 'via-router'],
  source: 'seed',
  verified: true,
});

export const BASE_SEED = [
  baseSvc({ target: 'coingecko', name: 'CoinGecko (token price)', capability: 'base:token-price', baseHost: 'pro-api.coingecko.com', baseUsd: 0.01, tags: ['prices', 'defi'],
    description: 'Live on-chain token price, market cap and 24h volume from CoinGecko’s Base DEX data. Append `?contract=0x…` (a Base token address). You pay ~0.5 KAS; the router settles CoinGecko’s $0.01 on Base and returns the data.' }),
  baseSvc({ target: 'tripadvisor', name: 'Tripadvisor (location details)', capability: 'base:travel', baseHost: 'tripadvisor.x402.paysponge.com', baseUsd: 0.01, tags: ['travel', 'places'],
    description: 'Tripadvisor details for a place — rating, reviews, address. Append `?locationId=…`. You pay ~0.5 KAS; the router settles $0.01 on Base.' }),
  baseSvc({ target: 'exa', name: 'Exa (neural web search)', capability: 'base:web-search', baseHost: 'api.exa.ai', baseUsd: 0.001, tags: ['search', 'web', 'ai'],
    description: 'Exa neural search + page contents. Pass the query as `?body={ "urls": ["https://…"] }`. You pay ~0.5 KAS; the router settles $0.001 on Base.' }),
  baseSvc({ target: 'thegraph', name: 'The Graph (subgraph query)', capability: 'base:subgraph', baseHost: 'gateway.thegraph.com', baseUsd: 0.01, tags: ['data', 'defi', 'graphql'],
    description: 'Query any subgraph on The Graph. Append `?subgraph_id=…` and `?body={ "query": "{ … }" }`. You pay ~0.5 KAS; the router settles $0.01 on Base.' }),
  baseSvc({ target: 'alchemy', name: 'Alchemy (JSON-RPC)', capability: 'base:rpc', baseHost: 'x402.alchemy.com', baseUsd: 0.001, tags: ['rpc', 'evm', 'node'],
    description: 'Alchemy JSON-RPC on any supported chain. Append `?chainNetwork=base-mainnet` and `?body={ "jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1 }`. You pay ~0.5 KAS; the router settles $0.001 on Base.' }),
  baseSvc({ target: 'parallel', name: 'Parallel (web search)', capability: 'base:web-search', baseHost: 'parallelmpp.dev', baseUsd: 0.01, tags: ['search', 'web'],
    description: 'Parallel web search. Pass the query as `?body={ "query": "…" }`. You pay ~0.5 KAS; the router settles $0.01 on Base.' }),
  baseSvc({ target: 'perplexity', name: 'Perplexity (answer engine)', capability: 'base:answer', baseHost: 'pplx.x402.paysponge.com', baseUsd: 0.01, tags: ['search', 'ai', 'answers'],
    description: 'Perplexity answer engine. Pass the query as `?body={ "query": "…" }`. You pay ~0.5 KAS; the router settles $0.01 on Base.' }),
  baseSvc({ target: 'deepgram', name: 'Deepgram (speech-to-text)', capability: 'base:transcribe', baseHost: 'deepgram.x402.paysponge.com', baseUsd: 1.0, tier: 'hi', tags: ['audio', 'transcription', 'ai'],
    description: 'Deepgram speech-to-text. Pass audio as `?body={ "url": "https://…/audio.wav" }`. Higher tier — you pay ~60 KAS; the router settles Deepgram’s $1.00 on Base.' }),
];
