// lib/listings.js — the marketplace's CURATED seed of x402 v2 services (option 1). You own this list;
// edit it to add/curate services you stand behind. Only REAL, verifiable x402 v2 endpoints belong here.
// (Open submissions from anyone are option 2 — see lib/registry.js — and are gated by a live /validate.)

const CHAT = 'https://kaspa-402-chat.kaspadev.workers.dev/exact';
const PAYTO = 'kaspa:qzws2a0lfhs9y8kkvyd4mm96gl733pd0mhzvh6mdejms7970gzrawmvjwpde4';

// One mainnet chat model, selected via ?model= on the shared chat gateway. Each model is priced
// independently (KASPA_X402_PRICE_USD_MAP on the gateway) — small models sit at the 0.5 KAS dust
// floor, larger ones command more; priceUsd here mirrors that map so the catalog matches the live offer.
const chatModel = (alias, name, capability, note, priceUsd) => ({
  id: `kaspa-402-chat-${alias}`,
  resource: `${CHAT}?model=${alias}`,
  serviceName: `Kaspa·402 — ${name}`,
  description: `${note} Append \`?prompt=…\` to the URL; each call settles $${priceUsd.toFixed(2)} (paid in KAS at the current rate, min 0.5 KAS) via x402 \`exact\` (standard-native) on mainnet and returns a reply.`,
  capability,
  scheme: 'exact',
  network: 'kaspa:mainnet',
  priceUsd,
  amountSompi: 50000000,
  payTo: PAYTO,
  tags: ['llm', 'mainnet', alias],
  source: 'seed',
  verified: true,
});

export const SEED = [
  {
    id: 'kaspa-402-summarize',
    resource: 'https://kaspa-402-summarize.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — summarize',
    description: 'Pay-per-call text summarization on llama3.1:8b, on kaspa:testnet-10 (validation target — settled in valueless TKAS). Append `?text=…` to the URL; each call settles a $0.05-equivalent amount (min 0.5 TKAS) via x402 `exact` (standard-native) and returns a 1–2 sentence summary.',
    capability: 'summarize',
    scheme: 'exact',
    network: 'kaspa:testnet-10',
    priceUsd: 0.05,
    amountSompi: 50000000,
    payTo: 'kaspatest:qr50gmc7t3jp33gg68aj63s9av54yc7w9kyjpwqdjhva9tt8j0a7wz2h6cnll',
    tags: ['llm', 'summarize', 'testnet'],
    source: 'seed',
    verified: true,
  },
  chatModel('chat', 'chat', 'llm:chat', 'General chat on llama3.1:8b.', 0.03),
  chatModel('fast', 'fast chat', 'llm:chat', 'Low-latency chat on qwen2.5:3b.', 0.01),
  chatModel('chat-mini', 'chat-mini', 'llm:chat', 'Balanced chat on qwen2.5:7b.', 0.01),
  chatModel('reason', 'reason', 'llm:reason', 'Deeper reasoning on qwen3.5:35b.', 0.08),
  chatModel('think', 'think', 'llm:reason', 'Reasoning-tuned qwen-think.', 0.10),
  chatModel('uncensored', 'uncensored', 'llm:chat', 'Unfiltered chat on Qwen3.6-35B.', 0.08),
  {
    id: 'kaspa-402-embed',
    resource: 'https://kaspa-402-embed.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — embed',
    description: 'Text embeddings on nomic-embed-text. Append `?input=…`; each call settles $0.01 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet and returns a 768-dim vector.',
    capability: 'embed',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.01,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['llm', 'embed', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-research',
    resource: 'https://kaspa-402-research.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — token risk report',
    description: 'On-chain due-diligence for KRC-20 tokens and KRC-721 NFTs — holder concentration, mint status, liquidity, and legitimacy signals, plus a plain-language risk summary. Append `?asset=krc20:NACHO` (or `krc721:KASPUNKS`); each call settles $0.10 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. On-chain facts, not financial advice.',
    capability: 'token-risk',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.10,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['research', 'krc20', 'krc721', 'risk', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-wallet',
    resource: 'https://kaspa-402-wallet.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — wallet risk profile',
    description: 'On-chain profile + risk read for any Kaspa address — KAS balance, activity, KRC-20 holdings, exposure to risky tokens (via the token-risk engine), and deployer detection. Append `?address=kaspa:…`; each call settles $0.10 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. On-chain facts from public data, not an accusation.',
    capability: 'wallet-risk',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.10,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['research', 'wallet', 'risk', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-ask',
    resource: 'https://kaspa-402-ask.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Kaspa expert (grounded Q&A)',
    description: "Grounded answers about Kaspa from a retrieval knowledge base — won't hallucinate Kaspa facts, and returns its sources. Append `?question=…`; each call settles $0.03 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. Ask about GHOSTDAG, KRC-20, covenants, Crescendo/Toccata, fees, and more.",
    capability: 'kaspa-expert',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.03,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['llm', 'kaspa-expert', 'rag', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-compare',
    resource: 'https://kaspa-402-compare.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — token comparison',
    description: 'Side-by-side risk comparison of 2–5 KRC-20 tokens — ranked safest-first on holder concentration, mint status, liquidity, and legitimacy, with a comparative writeup. Append `?assets=NACHO,KOMA,KANDA`; each call settles $0.15 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. On-chain facts, not financial advice.',
    capability: 'token-compare',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.15,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['research', 'krc20', 'compare', 'risk', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-radar',
    resource: 'https://kaspa-402-radar.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — mint & launch radar',
    description: "A live feed of what's hot and whether it's safe across KRC-20 tokens and KRC-721 NFTs — sorted by momentum (holder growth), recency, or minting activity, each with quick risk flags (pre-mint, tiny holder counts, still minting). Append `?type=krc20|krc721&sort=hot|new|minting&limit=10`; each call settles $0.05 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. On-chain facts, not financial advice.",
    capability: 'mint-radar',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.05,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['research', 'krc20', 'krc721', 'radar', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-ghost',
    resource: 'https://kaspa-402-ghost.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Ghost Trail (fund tracer)',
    description: "Follow the money. Feed a Kaspa address or a txid and trace the flow — top sources (who funded it), top destinations (who it paid), net flow, and distinct counterparties, with a forensic read. Append `?target=kaspa:…` (or a 64-hex txid); each call settles $0.10 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. Public on-chain data.",
    capability: 'fund-trace',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.10,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['forensics', 'trace', 'chain', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-shadow',
    resource: 'https://kaspa-402-shadow.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Whale Shadow (wallet tail)',
    description: "Tail a whale. Feed a Kaspa address and get a read on what it's doing right now — its size (KAS + KRC-20 holdings), whether it's accumulating or distributing KAS, and which tokens it's loading up on vs offloading. Append `?address=kaspa:…`; each call settles $0.10 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. Public on-chain data.",
    capability: 'whale-watch',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.10,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['forensics', 'whale', 'chain', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-coroner',
    resource: 'https://kaspa-402-coroner.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Rug Coroner (token autopsy)',
    description: "Token autopsy. Feed a KRC-20 ticker and get a health verdict — alive, critical, on life support, or likely dead — with the cause-of-death signs: liquidity failure, pre-mint, deployer holding, concentration, holder flight. Append `?ticker=KANDA`; each call settles $0.10 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. On-chain diagnosis from public data, not an accusation.",
    capability: 'rug-autopsy',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.10,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['forensics', 'rug', 'krc20', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-sybil',
    resource: 'https://kaspa-402-sybil.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Sybil Hunter',
    description: "Flag the bots. Feed a KRC-20 ticker and scan its holders for coordinated / sybil clusters — wallets holding identical amounts, the fingerprint of farms and insider distribution. Append `?ticker=KANDA`; each call settles $0.10 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. Top-holder sample; a suspicion signal, not proof.",
    capability: 'sybil-scan',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.10,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['forensics', 'sybil', 'krc20', 'mainnet'],
    source: 'seed',
    verified: true,
  },
  {
    id: 'kaspa-402-exposure',
    resource: 'https://kaspa-402-exposure.kaspadev.workers.dev/exact',
    serviceName: 'Kaspa·402 — Exposure Report (OPSEC score)',
    description: "How traceable are you? Feed a Kaspa address and get an OPSEC / traceability score — linked alter-egos (co-spending), counterparty footprint, on-chain surface — plus concrete hardening advice. Append `?address=kaspa:…`; each call settles $0.10 (paid in KAS at the current rate, min 0.5 KAS) via x402 `exact` on mainnet. Public on-chain data.",
    capability: 'opsec-score',
    scheme: 'exact',
    network: 'kaspa:mainnet',
    priceUsd: 0.10,
    amountSompi: 50000000,
    payTo: PAYTO,
    tags: ['forensics', 'opsec', 'privacy', 'mainnet'],
    source: 'seed',
    verified: true,
  },
];
